/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3a9c8758-e5c3-4c6e-bdfd-625012c8f2e4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_BkwMmb23d",
    "aws_user_pools_web_client_id": "5bndbedk9131kb3chpr9f2m08g",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "notegenius-bucket7e1f8-notegen",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
